{"name": "test_fail18", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail18():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:20: AssertionError"}, "start": 1694074753879, "stop": 1694074753879, "uuid": "0f896fa3-126f-40de-9c21-9fbb505f2666", "historyId": "f34bb12e2c558e2f7462552abc331e5e", "testCaseId": "f34bb12e2c558e2f7462552abc331e5e", "fullName": "tests.simple.test_fail#test_fail18", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "CHIRKINAA-E15G2"}, {"name": "thread", "value": "34640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}