{"name": "test_fail14", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail14():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:8: AssertionError"}, "start": 1694074702008, "stop": 1694074702008, "uuid": "575c0c1d-2ace-4f79-8b42-3157ac538cf7", "historyId": "aed55e29779fc943e5f040dfe1d5f371", "testCaseId": "aed55e29779fc943e5f040dfe1d5f371", "fullName": "tests.simple.test_fail#test_fail14", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "CHIRKINAA-E15G2"}, {"name": "thread", "value": "34640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}